version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lottery-service
      POSTGRES_USER: lottery-db
      POSTGRES_PASSWORD: lottery-db-pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  lottery-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - postgres

volumes:
  pgdata: